cart/urls.py
from .                          import views
from django.conf                import settings
from django.conf.urls.static    import static
from django.urls                import path, include

app_name = 'cart'

urlpatterns = [
#   Cart urls
    path('', views.home, name='home'),
    path('add/<int:id>/', views.cart_add, name='cart_add'),
    path('item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('item_increment/<int:id>/', views.item_increment, name='item_increment'),
    path('item_decrement/<int:id>/', views.item_decrement, name='item_decrement'),
    path('item_add/<int:id>', views.item_add, name='item_add'),
    path('clear/', views.cart_clear, name='cart_clear'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/urls.py
from django.urls    import path, include
from . import views

app_name = 'catalog'

urlpatterns = [
    path('detail/<int:product_id>/', views.detail, name='detail'),
    path('leavecomment/<int:product_id>', views.leave_comment, name='leave_comment'),
]

main/urls.py
from .                          import views
from django.conf                import settings
from django.conf.urls.static    import static
from django.contrib             import admin
from django.urls                import path, include

# App urls
import cart.urls    as cart_urls
import catalog.urls as catalog_urls
import order.urls   as order_urls
import user.urls    as user_urls


urlpatterns = [
    # Home page
    path('', views.home, name='home'),

    # Category
    path('category/<str:category>/', views.category, name='category'),

    # Search
    path('search/', views.search, name='search'),

    # Admin table
    path('admin/',  admin.site.urls),

    # Includes
    path('cart/',   include(cart_urls)),
    path('product/',include(catalog_urls)),
    path('checkout/',  include(order_urls)),
    path('user/',   include(user_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from .              import views
from django.urls    import path, include


app_name = 'order'

urlpatterns = [
    path('', views.home, name='home'),
    path('makeorder', views.make_order, name='makeorder'),
]

cart/views.py
from cart.cart              import Cart
from django.shortcuts       import render, redirect
from catalog.models         import product
from django.contrib         import messages
from django.conf            import settings


def home(request):
    return render(request, 'cart/cart.html', context = { 'TITLE' : 'Корзина' })


def cart_add(request, id):
    cart = Cart(request)
    Product = product.objects.get(id=id)
    cart.add(product=Product)
    messages.success(request, 'Вы успешно добавили продукт в корзину')
    return redirect(request.META.get('HTTP_REFERER'))


def item_clear(request, id):
    cart = Cart(request)
    Product = product.objects.get(id=id)
    cart.remove(Product)
    return redirect("cart:home")


def item_increment(request, id):
    cart = Cart(request)
    Product = product.objects.get(id=id)
    cart.add(product=Product)
    return redirect("cart:home")


def item_decrement(request, id):
    cart = Cart(request)
    Product = product.objects.get(id=id)
    cart.decrement(product=Product)
    return redirect("cart:home")


def item_add(request, id):
    cart = Cart(request)
    Product = product.objects.get(id=id)
    quantity = int(request.POST.get('quantity'))
    if quantity <= 0 or quantity > Product.on_stock:
        cart.remove(product=Product)
    else:
        cart.add(product=Product, quantity=quantity)
    return redirect('cart:home')


def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect("cart:home")

templates/cart/cart.html
{% extends 'base.html' %}
{% load static %}
{% load cart_tag %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/cart.css' %}">
{% endblock style %}

{% block header %}{% endblock header %}

{% block main %}
    <h2 class="text-center mt-5 pt-5">Корзина</h2>
    
    {% if request.session.cart %}
        <table class="table table-hover">
            <!-- Table head -->
            <tr>
                <th>Название</th>
                <th>Количество</th>
                <th class="text-center">Цена</th>
                <th class="text-center">Всего</th>
                <th> </th>
            </tr>
            <!-- Table Body -->
            {% for amount, product in request.session.cart.items %}
                <tr>
                    <td class="col-sm-8 col-md-6">
                        <div class="media">
                            <a href="{% url 'catalog:detail' product.product_id %}" class="thumbnail mr-1">
                                <img src="{{ product.image }}" alt="{{ product.name }}" class="media-object" style="width: 75px; height: 72px;">
                            </a>
                            <div class="media-body">
                                <h4 class="media-heading"><a href="{% url 'catalog:detail' product.product_id %}">{{ product.name }}</a></h4>
                                <div>
                                    Количество товара на складе: <strong class="text-success">{{ product.on_stock }} шт.</strong>
                                </div>
                            </div>
                        </div>
                    </td>

                    <td class="col-sm-1 col-md-1 text-center">
                        <form action="{% url 'cart:item_add' product.product_id %}" method="POST">
                            {% csrf_token %}
                            <input type="number" name="quantity" id="product_quantity" class="form-control" value="{{ product.quantity }}" max="{{ product.on_stock }}" min="0" required>
                        </form>
                    </td>

                    <td class="col-sm-1 col-md-1 text-center">
                        <strong>{{ product.price }}&#8381;</strong>
                    </td>

                    <td class="col-sm-1 col-md-1 text-center">
                        <strong id="product_total">{{ product.price|multiply:product.quantity|floatformat:2 }}&#8381;</strong>
                    </td>

                    <td class="col-sm-1 col-md-1">
                        <a class="btn btn-danger" href="{% url 'cart:item_clear' product.product_id %}"><i class="fas fa-trash-alt"></i></a>
                    </td>
                </tr>
            {% endfor %}
            <!-- Useles for a while -->
            <!--
            <tr>
                <td colspan="4">
                    <h5>Подытог</h5>
                </td>
                <td class="text-right">
                    <h5 class="font-weight-bold">{{ cart_total_amount }}&#8381;</h5>
                </td>
            </tr>

            <tr>
                <td colspan="4">
                    <h5>Стоимость доставки</h5>
                </td>
                <td class="text-right">
                    <h5 class="font-weight-bold">228 &#8381;</h5>
                </td>
            </tr>
            -->

            <tr>
                <td colspan="2">
                    <h3>Всего</h3>
                </td>
                <td colspan="3" class="text-right">
                    <h3 class="font-weight-bold" id="total">{{ cart_total_amount|floatformat:2 }} &#8381;</h3>
                </td>
            </tr>
        </table>

        <div class="w-100 clearfix">
            <a class="btn btn-default float-sm-left" href="{% url 'home' %}">
                <i class="fas fa-shopping-cart mr-2"></i>Продолжить покупки
            </a>

            <a href="{% url 'cart:cart_clear' %}" class="btn btn-danger">
                <i class="fas fa-trash-alt mr-2"></i>Очистить корзину
            </a>

            <a class="btn btn-success float-sm-right" href="{% url 'order:home' %}">
                Оформить заказ
            </a>
        </div>
    {% else %}
        <p class="text-muted text-center">
            Ваша корзина пуста

            <br>
        
            <a class="btn btn-default m-auto" href="{% url 'home' %}">
                <i class="fas fa-shopping-cart mr-2"></i>Продолжить покупки
            </a>
        </p>
    {% endif %}
{% endblock main %}

{% block script %}
    <script>
        
    </script>
{% endblock script %}