cart/urls.py
from .                          import views
from django.conf                import settings
from django.conf.urls.static    import static
from django.urls                import path, include

app_name = 'cart'

urlpatterns = [
#   Cart urls
    path('', views.home, name='home'),
    path('add/<int:id>/', views.cart_add, name='cart_add'),
    path('item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('item_increment/<int:id>/', views.item_increment, name='item_increment'),
    path('item_decrement/<int:id>/', views.item_decrement, name='item_decrement'),
    path('item_add/<int:id>', views.item_add, name='item_add'),
    path('clear/', views.cart_clear, name='cart_clear'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from .                          import views
from django.conf                import settings
from django.conf.urls.static    import static
from django.contrib             import admin
from django.urls                import path, include

# App urls
import cart.urls    as cart_urls
import catalog.urls as catalog_urls
import order.urls   as order_urls
import user.urls    as user_urls


urlpatterns = [
    # Home page
    path('', views.home, name='home'),

    # Category
    path('category/<str:category>/', views.category, name='category'),

    # Search
    path('search/', views.search, name='search'),

    # Admin table
    path('admin/',  admin.site.urls),

    # Includes
    path('cart/',   include(cart_urls)),
    path('product/',include(catalog_urls)),
    path('checkout/',  include(order_urls)),
    path('user/',   include(user_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from .              import views
from django.urls    import path, include


app_name = 'order'

urlpatterns = [
    path('', views.home, name='home'),
    path('makeorder', views.make_order, name='makeorder'),
]

order/models.py
from catalog.models import product
from django.contrib.auth.forms import User
from django.db      import models
from catalog.models import product


class order(models.Model):
    user    = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, verbose_name='Пользователь')
    fio     = models.CharField('ФИО пользователя', max_length=256)
    total   = models.FloatField('Итоговая стоимость')
    address = models.CharField('Адрес доставки', max_length=256)
    post_code = models.CharField('Почтовый код', max_length=10)
    date    = models.DateField('Дата оформления заказа', auto_now=True)

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'
    
    def __str__(self):
        return self.fio


class order_product(models.Model):
    order    = models.ForeignKey(order, on_delete=models.CASCADE, verbose_name='Код заказа')
    product  = models.ForeignKey(product, null=True, on_delete=models.SET_NULL, verbose_name='Код продукта')
    quantity = models.PositiveIntegerField('Количество')

order/forms.py
from .models    import order
from django     import forms
from user.models import UserProfile


class MakeOrderForm(forms.ModelForm):
    
    class Meta:
        model = UserProfile
        fields = ['address', 'phone', 'post_index']

order/views.py
from .                  import forms
from .models            import order, order_product
from cart.cart          import Cart
from cart.context_processor import get_total
from catalog.models     import product
from django.contrib     import messages
from django.shortcuts   import render, redirect


def home(request):
    if request.user.is_authenticated:
        return render(request, 'order/index.html', { 'TITLE' : 'Оформление заказа' })
    else:
        messages.error(request, 'Вы должны быть авторизированы, что бы оформить заказ')
        return redirect('home')


def make_order(request):
    if request.user.is_authenticated:
        Order = order(
            user=request.user,
            fio=request.POST.get('fio'),
            total=get_total(request),
            address=request.POST.get('address'),
            post_code=request.POST.get('post_code')
        )
        Order.save()
        for code, item in request.session['cart'].items():
            Product = product.objects.get(pk=item['product_id'])

            Product_order = order_product.objects.create(order=Order, product=Product, quantity=item['quantity'])
            Product_order.save()

            Product.was_bought(item['quantity'])
            Product.save()
    else:
        messages.error(request, 'Вы должны быть авторизированы, что бы оформить заказ')
        return redirect('user:login')

    cart = Cart(request)
    cart.clear()

    messages.success(request, 'Заказ успешно оформлен')
    return redirect('user:my_orders')

templates/order/index.html
{% extends 'base.html' %}
{% block main %}
{% load static %}
{% load cart_tag %}

<section class="mt-5 pt-5">
    <form action="{% url 'order:makeorder' %}" method="POST" class="col-md-8 border border-light p-md-3 m-auto">
        <h2 class=" text-center">{{ TITLE }}</h2>

        {% csrf_token %}

        <div class="md-form form-group">
            <label for="fio">ФИО</label>
            <input type="text"
                id="fio"
                name="fio"
                required
                value="{{ user.last_name }} {{ user.first_name }}"
                class="form-control my-2"
                >
        </div>

        <div class="md-form form-group">
            <label for="address">Адрес доставки</label>
            <input type="text"
                id="address"
                name="address"
                required
                value="{{ profile.address }}"
                class="form-control my-2"
            >
        </div>

        <div class="md-form form-group">
            <label for="post_code">Почтовый код</label>
            <input type="text"
                id="post_code"
                name="post_code"
                required
                value="{{ profile.post_code }}"
                class="form-control my-2"
            >
        </div>

        <h2>Заказ на общую сумму: <b>{{ cart_total_amount }}&#8381;</b></h2>
        <div class="text-center">
            <button type="submit" href="{% url 'order:makeorder' %}" class="btn btn-success m-auto">Оформить заказ</button>
        </div>
    </form>
</section>
{% endblock main %}