cart/urls.py
from .                          import views
from django.conf                import settings
from django.conf.urls.static    import static
from django.urls                import path, include

app_name = 'cart'

urlpatterns = [
#   Cart urls
    path('', views.home, name='home'),
    path('add/<int:id>/', views.cart_add, name='cart_add'),
    path('item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('item_increment/<int:id>/', views.item_increment, name='item_increment'),
    path('item_decrement/<int:id>/', views.item_decrement, name='item_decrement'),
    path('item_add/<int:id>', views.item_add, name='item_add'),
    path('clear/', views.cart_clear, name='cart_clear'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/urls.py
from django.urls    import path, include
from . import views

app_name = 'catalog'

urlpatterns = [
    path('detail/<int:product_id>/', views.detail, name='detail'),
    path('leavecomment/<int:product_id>', views.leave_comment, name='leave_comment'),
]

main/urls.py
from .                          import views
from django.conf                import settings
from django.conf.urls.static    import static
from django.contrib             import admin
from django.urls                import path, include

# App urls
import cart.urls    as cart_urls
import catalog.urls as catalog_urls
import order.urls   as order_urls
import user.urls    as user_urls


urlpatterns = [
    # Home page
    path('', views.home, name='home'),

    # Category
    path('category/<str:category>/', views.category, name='category'),

    # Search
    path('search/', views.search, name='search'),

    # Admin table
    path('admin/',  admin.site.urls),

    # Includes
    path('cart/',   include(cart_urls)),
    path('product/',include(catalog_urls)),
    path('checkout/',  include(order_urls)),
    path('user/',   include(user_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from .              import views
from django.urls    import path, include


app_name = 'order'

urlpatterns = [
    path('', views.home, name='home'),
    path('makeorder', views.make_order, name='makeorder'),
]

user/urls.py
from .                      import views
from django.urls            import path, include
from django.contrib.auth    import views as auth_views

app_name = 'user'

urlpatterns = [
    # profile
    path('', views.home, name='home'),
    path('edit/',    views.edit, name = 'edit'),
    path('forget_password/', auth_views.PasswordResetView.as_view(template_name='user/form.html', extra_context={ 'TITLE' : 'Восстановление пароля' }), name = 'restore_password'),
    path('login/',   views.login, name = 'login'),
    path('logout/',  auth_views.LogoutView.as_view(), name = 'logout'),
    path('register/', views.register, name='register'),
    path('registrate/', views.registrate, name='registrate'),
    path('delete/', views.del_profile, name="del_profile"),
    path('edit_profile/', views.edit_profile, name='edit_profile'),

    # Favorites
    path('favorites/', views.favorites, name='favorites'),
    path('addfavorite/<int:product_id>', views.add_to_fav, name='add_to_fav'),
    path('delfavorite/<int:product_id>', views.del_from_fav, name='del_from_fav'),

    # My orders
    path('orders/', views.my_orders, name='my_orders'),
]

order/models.py
from catalog.models import product
from django.contrib.auth.forms import User
from django.db      import models
from catalog.models import product


class order(models.Model):
    user    = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, verbose_name='Пользователь')
    fio     = models.CharField('ФИО пользователя', max_length=256)
    total   = models.FloatField('Итоговая стоимость')
    address = models.CharField('Адрес доставки', max_length=256)
    post_code = models.CharField('Почтовый код', max_length=10)
    date    = models.DateField('Дата оформления заказа', auto_now=True)

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'
    
    def __str__(self):
        return self.fio


class order_product(models.Model):
    order    = models.ForeignKey(order, on_delete=models.CASCADE, verbose_name='Код заказа')
    product  = models.ForeignKey(product, null=True, on_delete=models.SET_NULL, verbose_name='Код продукта')
    quantity = models.PositiveIntegerField('Количество')

user/models.py
from django.db                  import models
from django.contrib.auth.models import User
from catalog.models             import product


class UserProfile(models.Model):
    user        = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar      = models.ImageField('Аватар пользователя', upload_to='user', null=False, default='avatar_default.png')
    address     = models.CharField('Адрес доставки', max_length=512, blank=True, null=True, default='Не указан')
    phone       = models.CharField('Номер телефона', max_length=12, blank=True, null=True, default='Не указан')
    post_index  = models.CharField('Почтовый индекс', max_length=7, blank=True, null=True, default='Не указан')

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

    def __str__(self):
        return str(self.user)



class Favorites(models.Model):
    user        = models.OneToOneField(User, on_delete=models.CASCADE)
    favorite    = models.ManyToManyField(product)

    class Meta:
        verbose_name = 'Избранное'
        verbose_name_plural = 'Избранные'

    def __str__(self):
        return str(self.user)

order/forms.py
from .models    import order
from django     import forms
from user.models import UserProfile


class MakeOrderForm(forms.ModelForm):
    
    class Meta:
        model = UserProfile
        fields = ['address', 'phone', 'post_index']

user/forms.py
from .models                        import UserProfile
from django                         import forms
from django.contrib.auth.models     import User


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['avatar', 'address', 'phone', 'post_index']

order/views.py
from .                  import forms
from .models            import order, order_product
from cart.cart          import Cart
from cart.context_processor import get_total
from catalog.models     import product
from django.contrib     import messages
from django.shortcuts   import render, redirect


def home(request):
    if request.user.is_authenticated:
        return render(request, 'order/index.html', { 'TITLE' : 'Оформление заказа' })
    else:
        messages.error(request, 'Вы должны быть авторизированы, что бы оформить заказ')
        return redirect('home')


def make_order(request):
    if request.user.is_authenticated:
        Order = order(
            user=request.user,
            fio=request.POST.get('fio'),
            total=get_total(request),
            address=request.POST.get('address'),
            post_code=request.POST.get('post_code')
        )
        Order.save()
        for code, item in request.session['cart'].items():
            Product = product.objects.get(pk=item['product_id'])

            Product_order = order_product.objects.create(order=Order, product=Product, quantity=item['quantity'])
            Product_order.save()

            Product.was_bought(item['quantity'])
            Product.save()
    else:
        messages.error(request, 'Вы должны быть авторизированы, что бы оформить заказ')
        return redirect('user:login')

    cart = Cart(request)
    cart.clear()

    messages.success(request, 'Заказ успешно оформлен')
    return redirect('user:my_orders')

user/views.py
from django.contrib.auth.forms  import User
from django.shortcuts           import render, redirect, get_list_or_404, get_object_or_404
from django.contrib.auth        import authenticate, login as auth_login
from django.contrib             import messages
from .models                    import UserProfile, Favorites
from catalog.models             import product
from .forms                     import EditProfileForm


def home(request):
    return render(request, 'user/index.html', { 'TITLE' : 'Моя страница'})


def login(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                auth_login(request, user)
                messages.success(request, 'Вы успешно авторизировались')
            else:
                messages.error(request, 'Что-то пошло не так, мы не смогли вас авторизовать 😥')
    else:
        messages.error(request, 'Вы уже авторизованы')
        
    return redirect('home')


def register(request):
    return render(request, 'user/register.html', { 'TITLE' : 'Регистрация нового пользователя' })


def registrate(request):
    if request.POST.get('password') == request.POST.get('confirm'):
        user = User.objects.create_user(
            username= request.POST.get('username'),
            email= request.POST.get('email'),
            password= request.POST.get('password'),
            first_name= request.POST.get('first_name'),
            last_name= request.POST.get('last_name')
        )
        if user:
            messages.success(request, 'Профиль успешно создан')
            auth_login(request, user)
            profile = UserProfile(user=user)
            profile.save()

            favorite = Favorites(user=user)
            favorite.save()
        else:
            messages.success(request, 'Произошла ошибка создание профиля')
        return redirect('home')
    else:
        messages.error(request, 'Пароли не совпадают')
        return redirect('user:register')


def edit(request):
    form = EditProfileForm()
    return render(request, 'user/edit_profile.html', { 'TITLE' : 'Изменение информации профиля', 'form' : form })


def edit_profile(request):
    if request.method == 'POST':

        user = request.user

        profile = UserProfile.objects.filter(user=user)
        profile.set(avatar=request.POST.get('avatar'), adress=request.POST.get('adress'), phone=request.POST.get('phone'), post_index=request.POST.get('post_index'))
        profile.save()

        messages.success(request, 'Изменения сохранены')
    else:
        messages.error(request, 'Никакие данные не были введены')
    return redirect('user:home')


def del_profile(request):
    user = request.user
    try:
        user.delete()
        messages.success(request, 'Профиль успешно удалён')
    except:
        messages.error(request, 'Произошла ошибка удаления профиля')
    return redirect('home')


def favorites(request):
    return render(request, 'user/favorites.html', { 'TITLE' : 'Избранное', 'catalog' : get_list_or_404(Favorites ,user=request.user) })


def add_to_fav(request, product_id):
    if request.user.is_authenticated:
        item = get_object_or_404(product, id=product_id)
        fav = Favorites(user=request.user)
        fav.favorite.set(item)
        fav.save()

        messages.success(request, 'Продукт успешно добавлен в избранное')

    else:
        messages.error(request, 'Вы должны быть авторизованы что бы добавить продукт в избранное')
        return redirect('home')
    return redirect(request.META.get('HTTP_REFERER', '/'))


def del_from_fav(request, product_id):
    item = get_object_or_404(product)
    fav = Favorites(user=request.user, favorite=item)
    fav.delete()
    return redirect(request.META.get('HTTP_REFERER', '/'))


def my_orders(request):
    return render(request, 'user/orders.html', { 'TITLE' : 'Мои заказы' })

templates/user/edit_profile.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
{% endblock style %}

{% block main %}

<h2 class="mt-5 pt-4 text-center">Изменение информации профиля</h2>
<section class="col-md-8 m-auto">
    <p class="text-muted text-center">Функция находится в разработке</p>
<!--
    <form action="{% url 'user:edit_profile' %}" method="POST" class="text-center border border-light p-md-3">

        {% csrf_token %}

        <h3>Основная информация</h3>
        <div class="md-form form-group">
            <label for="second_name">Фамилия</label>
            <input type="text" 
                class="form-control mb-2"
                id="second_name"
                maxlength="30"
                name="second_name"
                required
                value="{{ user.last_name }}">
        </div>

        <div class="md-form form-group">
            <label for="first_name">Имя</label>
            <input type="text"
                class="form-control my-2"
                id="first_name"
                maxlength="150"
                name="first_name"
                required
                value="{{ user.first_name }}">
        </div>

        <div class="md-form form-group">
            <label for="email">Адрес электронной почты</label>
            <input type="email"
                class="form-control my-2"
                id="email"
                name="email"
                required
                value="{{ user.email }}">
        </div>
        


        <h3 class="mt-5">Дополнительная информация</h3>

        <div class="custom-file">
            <input type="file"
                class="custom-file-input my-2"
                name="avatar"
                id="avatar">
            <label class="custom-file-label" for="avatar">Аватар</label>
        </div>


        <div class="md-form">
            <label for="">Адрес доставки</label>
            <input type="text"
                class="form-control"
                id="adress"
                maxlength="256"
                name="adress"
            >
        </div>

        <div class="md-form">
            <label for="">Телефон</label>
            <input type="text"
                class="form-control"
                id="phone"
                maxlength="256"
                name="phone"
            >
        </div>

        <div class="md-form">
            <label for="post_index">Почтовый индекс</label>
            <input type="text"
                class="form-control mt-2"
                id="post_index" 
                maxlength="6"
                name="post_index"
                value="{{ profile.post_index }}">
        </div>

        <button type="submit" class="btn btn-success mt-5"><i class="far fa-save mr-1"></i>Сохранить</button>
    </form>
-->
    <div class="text-center">
        <a href="{% url 'user:del_profile' %}" class="btn btn-danger"><i class="fas fa-trash mr-1"></i>Удалить профиль</a>
    </div>
</section>

{% endblock main %}

{% block script %}
    <script src="{% static 'js/jquery.maskedinput.min.js' %}"></script>
    <script>
        $('#phone').mask('+7(999)-999-99-99', { autoclear : false, placeholder : 'X' });
    </script>
{% endblock script %}

templates/user/favorites.html
{% extends 'base.html' %}
{% load static %}

{% block main %}
    <h2 class="mt-5 pt-4">{{ TITLE }}</h2>

    <section>
        {% if catalog %}
            <table class="table table-hover">
                <!-- Table Body -->
                {% for product in catalog %}
                    <tr>
                        <td class="col-sm-8 col-md-6">
                            <div class="media">
                                <a href="{% url 'catalog:detail' product.id %}" class="thumbnail mr-1">
                                    <img src="{{ product.image.url }}" alt="{{ product.name }}" class="media-object" style="width: 75px; height: 72px;">
                                </a>
                                <div class="media-body">
                                    <h4 class="media-heading"><a href="{% url 'catalog:detail' product.id %}">{{ product.name }}</a></h4>
                                    <div>
                                        Количество товара на складе: <strong class="text-success">{{ product.on_stock }}</strong>
                                    </div>
                                </div>
                            </div>
                        </td>
                        
                        <td class="col-sm-1 col-md-1 text-center">
                            <strong>{{ product.price }}&#8381;</strong>
                        </td>

                        <td class="col-sm-2 col-md-2">
                            <a href="#" class="btn btn-default">
                                <i class="fa fa-shopping-cart mr-1"></i>
                            </a>
                        </td>

                        <td class="col-sm-1 col-md-1">
                            <a class="btn btn-danger" href="{% url 'cart:item_clear' product.id %}"><i class="fas fa-trash-alt"></i></a>
                        </td>
                    </tr>
                
                {% endfor %}
            </table>
        {% else %}
            <p class="text-muted text-center">Вы ничего не добавили в избранное</p>
        {% endif %}

                
    </section>
{% endblock main %}

templates/user/index.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
{% endblock style %}

{% block header %}
{% endblock header %}

{% block main %}
    <h2 class="text-center pt-5 mt-4">Привет, {{ user.username }}</h2>

    <section>
        <div class="row">
        
            <div class="col-md-3">
                <div class="view overlay z-depth-1 rounded-circle">
                    <img src="{{ profile.avatar.url }}" alt="{{ profile.user.username }}" class="img img-fluid">
                </div>
            </div>

            <div class="col-md-9">

                <table>
                    <tr>
                        <th class="pr-1 font-weight-bold">Фамилия:</th>
                        <td class="text-left">{{ user.last_name }}</td>
                    </tr>
                    <tr>
                        <th class="pr-1 font-weight-bold">Имя:</th>
                        <td class="text-left">{{ user.first_name }}</td>
                    </tr>
                    <tr>
                        <th class="pr-1 font-weight-bold">Адрес электронной почты:</th>
                        <td class="text-left">{{ user.email }}</td>
                    </tr>
                    <tr>
                        <th class="pr-1 font-weight-bold">Адрес доставки:</th>
                        <td class="text-left">{{ profile.adress }}</td>
                    </tr>
                    <tr>
                        <th class="pr-1 font-weight-bold">Почтовый индекс:</th>
                        <td class="text-left">{{ profile.post_index }}</td>
                    </tr>
                </table>

                <a href="{% url 'user:edit' %}" class="btn btn-default mx-0"><i class="fas fa-cog mr-1"></i>Настроить профиль</a>
            </div>
        </div>
    </section>
{% endblock main %}

{% block script %}
{% endblock script %}

templates/user/orders.html
{% extends 'base.html' %}
{% load static %}
{% load cart_tag %}

{% block main %}

    <section>
        <h2 class="text-center pt-5 mt-5">{{ TITLE }}</h2>
        
        {% if user.order_set.all %}
        
        <!-- Table -->
        <table class="table table-hover">
            <!-- Table body -->
            {% for item in user.order_set.all %}
            
            <!-- String -->
            <tr>
                <td class="col-sm-8 col-md-6">

                <div class="">
                Заказ от <time class="text-muted">{{ item.date }}</time> {{ item.order_product_set.all.count }} ед. товаров на общую сумму <b>{{ item.total }}&#8381;</b>
                </div>
                

                {% for order in item.order_product_set.all %}
                <div class="media my-2">

                    <a href="{% url 'catalog:detail' order.product.id %}" class="thumbnail mr-1">
                        <img src="{{ order.product.image.url }}" alt="{{ order.product.name }}" class="media-object" style="width: 75px; height: 72px;">
                    </a>

                    <div class="media-body">
                        <div class="row">
                        <div class="col-md-3">
                            <h4 class="media-heading"><a href="{% url 'catalog:detail' order.product.id %}" class="text-primary">{{ order.product.name }}</a></h4>
                            <p class="h4 font-weight-bold">{{ order.product.get_price }}&#8381;</p>
                        </div>
                        <div class="col-md-9">
                            <p class="mb-0"><strong>Количество:</strong> {{ order.quantity }} шт.</p>
                            <p class="mb-0"><strong>Итого:</strong> {{ order.product.get_price|multiply:order.quantity }}&#8381;</p>
                        </div>
                        </div>
                    </div>
                        
                </div>
                {% endfor %}

                </td>

            </tr>
            <!-- /String -->

            {% endfor %}
            <!-- /Table body -->
        </table>

        {% else %}
        <p class="text-center text-muted">Вы, пока что, ничего не заказали</p>
        {% endif %}

        <div class="text-center">
            <a href="{% url 'home' %}" class="btn btn-default"><i class="fa fa-shopping-cart mr-1"></i>Продолжить покупки</a>
        </div>

    </section>
{% endblock main %}

templates/user/register.html
{% extends 'base.html' %}
{% load static %}

{% block main %}
    <h2 class="text-center mt-5 pt-4">Регистрация нового пользователя</h2>

    <section>
    
        <form action="{% url 'user:registrate' %}" method="POST" class="text-center border border-light p-md-3 col-md-8 m-auto mb-3">
        
            {% csrf_token %}

            <div class="md-form form-group">
                <label for="username">Имя пользователя</label>
                <input type="text" name="username" id="username" class="validate form-control" required>
            </div>

            <div class="md-form form-group">
                <label for="email">Адрес электронной почты</label>
                <input type="email" name="email" id="email" class="validate form-control" required>
            </div>

            <div class="md-form form-group">
                <label for="password">Пароль</label>
                <input type="password" name="password" id="password" class="validate form-control" required>
            </div>

            <div class="md-form form-group">
                <label for="confirm">Подтвердите пароль</label>
                <input type="password" name="confirm" id="confirm" class="validate form-control" required>
            </div>

            <div class="md-form form-group">
                <label for="first_name">Имя</label>
                <input type="text" name="first_name" id="first_name" class="validate form-control" required>
            </div>

            <div class="md-form form-group">
                <label for="last_name">Фамилия</label>
                <input type="text" name="last_name" id="last_name" class="validate form-control" required>
            </div>

            <button type="submit" class="btn btn-success m-auto">
                <span class="fas fa-save mr-1"></span>Зарегистрироваться
            </button>
        </form>
    </section>
{% endblock main %}