cart/urls.py
from .                          import views
from django.conf                import settings
from django.conf.urls.static    import static
from django.urls                import path, include

app_name = 'cart'

urlpatterns = [
#   Cart urls
    path('', views.home, name='home'),
    path('add/<int:id>/', views.cart_add, name='cart_add'),
    path('item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('item_increment/<int:id>/', views.item_increment, name='item_increment'),
    path('item_decrement/<int:id>/', views.item_decrement, name='item_decrement'),
    path('item_add/<int:id>', views.item_add, name='item_add'),
    path('clear/', views.cart_clear, name='cart_clear'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/urls.py
from django.urls    import path, include
from . import views

app_name = 'catalog'

urlpatterns = [
    path('detail/<int:product_id>/', views.detail, name='detail'),
    path('leavecomment/<int:product_id>', views.leave_comment, name='leave_comment'),
]

main/urls.py
from .                          import views
from django.conf                import settings
from django.conf.urls.static    import static
from django.contrib             import admin
from django.urls                import path, include

# App urls
import cart.urls    as cart_urls
import catalog.urls as catalog_urls
import order.urls   as order_urls
import user.urls    as user_urls


urlpatterns = [
    # Home page
    path('', views.home, name='home'),

    # Category
    path('category/<str:category>/', views.category, name='category'),

    # Search
    path('search/', views.search, name='search'),

    # Admin table
    path('admin/',  admin.site.urls),

    # Includes
    path('cart/',   include(cart_urls)),
    path('product/',include(catalog_urls)),
    path('checkout/',  include(order_urls)),
    path('user/',   include(user_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.contrib.auth.forms import User
from django.db          import models
from django.shortcuts   import get_list_or_404
from django.conf        import settings


class product_type(models.Model):
    verbose = models.CharField('Название', max_length=75)
    plural  = models.CharField('Название мн. ч', max_length=75)
    name    = models.CharField('Название исп. для ссылок', max_length=50)

    class Meta:
        verbose_name = 'Тип продукта'
        verbose_name_plural = 'Типы продуктов'

    def __str__(self):
        return self.verbose


class product(models.Model):
    name            = models.CharField('Название', max_length=30, null=False, blank=False)
    description     = models.TextField('Описание', max_length=250, null=True, blank=True)
    price           = models.FloatField('Цена', null=False, blank=False)
    sale            = models.PositiveIntegerField('Скидка (указывать в процентах)', null=True, blank=True)
    image           = models.ImageField('Превью', upload_to='product', null=False, blank=False, default='default.png')
    on_stock        = models.PositiveIntegerField('Доступно на складе')
    avalible        = models.BooleanField('Доступно для покупки', default=bool(on_stock))
    product_type    = models.ForeignKey(product_type, verbose_name='Тип продукта', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    def __str__(self):
        return self.name

    def get_price(self):
        if self.sale:
            if 0 < self.sale < 100:
                return round(self.price - (self.price * (self.sale / 100)), 2)
            else:
                return 0
        else:
            return self.price

    def get_rate(self):
        if self.comment_set.all():
            result = [a.rate for a in self.comment_set.all()]
            return self.comment_set.all().rate / self.comment_set.count()
    
    def was_bought(self, amount):
        if self.on_stock >= amount:
            self.on_stock -= amount
            if self.on_stock == 0:
                self.avalible = False
        else: raise ValueError

        


class thumbnail(models.Model):
    product = models.ForeignKey(product, verbose_name='Продукт', on_delete=models.CASCADE)
    image   = models.ImageField('Изображение', upload_to='thumbnail')

    class Meta:
        verbose_name = 'Изображение'
        verbose_name_plural = 'Изображения'

    def __str__(self):
        return self.product


class paramether(models.Model):
    name = models.CharField('Название', max_length=50)
    units = models.CharField('Еденицы измерения', max_length=10)
    
    class Meta:
        verbose_name = 'Параметр'
        verbose_name_plural = 'Параметры'

    def __str__(self):
        return self.name


class characteristic(models.Model):
    product = models.ForeignKey(product, verbose_name='Продукт', on_delete=models.CASCADE)
    paramether = models.ForeignKey(paramether, verbose_name='Параметр', on_delete=models.CASCADE)
    value   = models.CharField('Значение параметра', max_length=150)

    class Meta:
        verbose_name = 'Характеристика'
        verbose_name_plural = 'Характеристики'

    def __str__(self):
        return str(self.value)


class comment(models.Model):
    product = models.ForeignKey(product, verbose_name='Продукт', on_delete=models.CASCADE)
    author  = models.ForeignKey(User, verbose_name='Автор', on_delete=models.CASCADE)
    text    = models.CharField('Текст комментария', max_length=150)
    date    = models.DateField('Дата оставления заказа', auto_now=True)
    rate    = models.SmallIntegerField('Оценка')

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return str(self.product)

    def get_star_bright(self):
        return range(self.rate)

    def get_star_dusk(self):
        return range(5 - self.rate)

catalog/views.py
from django.shortcuts   import render, get_object_or_404, HttpResponse, redirect
from catalog.models     import product, comment
from django.contrib     import messages


def detail(request, product_id):
    result = get_object_or_404(product, pk=product_id)
    return render(request, 'catalog/detail.html', { 'TITLE' : result.name, 'product' : result })


def leave_comment(request, product_id):
    if request.user.is_authenticated:
        commentary = comment(product=product.objects.get(pk=product_id), author=request.user, text=request.POST.get('text'), rate=request.POST.get('rate'))
        commentary.save()
    else:
        messages.error(request, 'Вы должны быть авторизированы что бы оставлять комментарии')
        return redirect('user:login')
    return redirect(request.META.get('HTTP_REFERER'))

templates/catalog/category.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
{% endblock style %}

{% block main %}
    <section class="text-center mb-4">

    <h2 class="text-center"><a name="catalog">Каталог</a></h2>

    <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Категории:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav" aria-controls="basicExampleNav"
          aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link mr-1" href="/">Всё
                <span class="sr-only">(текущая)</span>
              </a>
            </li>
            {% for item in PRODUCT_TYPE %}
                <li class="nav-item{% if TITLE == item.verbose %} active{% endif %}">
                    <a class="nav-link mx-1" href="{% url 'category' item.name %}#catalog">{{ item.plural }}</a>
                </li>
            {% endfor %}
          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Поиск" aria-label="Search" name="query">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->
      {% if catalog %}
      <div class="row wow fadeIn">
      
        <!-- Catalog -->
          {% for item in catalog %}
          <div class="col-lg-3 col-md-6 mb-4">
            <!-- Card -->
            <div class="card">
                <!-- Imgae -->
                <div class="view overlay">
                  <img src="{{ item.image.url  }}" class="img-fluid" alt="{{ item.name }}">
                  <a href="{% url 'catalog:detail' item.id %}">
                    <div class="mask rgba-white slight"></div>
                  </a>
                </div>
                <!-- Content -->
                <div class="card-body text-center">
                  <a href="{% url 'category' item.product_type.name %}" class="text-grey">{{ item.product_type.verbose }}</a>

                  <a href="{% url 'catalog:detail' item.id %}" class="grey-text ">
                    <h5>{{ item.name }}</h5>
                  </a>

                  {% if item.sale %} <h6 class="text-grey"><del>{{ item.price }}</del> &#8381;</h6>{% endif %}
                  <h4 class="font-weight-bold primary-text">{{ item.get_price|floatformat:2 }} &#8381;
                  {% if item.sale %} <span class="badge red z-depth-1 ml-1 rounded-pill">-{{ item.sale }}%</span> {% endif %}</h4>
                </div>
            </div>
          </div>
          {% endfor %}
        </div>

      {% else %}
        <div class="text-mute text-center">
          Продуктов нет
      </div>
      {% endif %}
      
    </section>
{% endblock main %}

{% block script %}
{% endblock script %}

templates/catalog/detail.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/detail.css' %}">
{% endblock style %}

{% block header %}
{% endblock header %}

{% block main %}
    <div class="row mt-5 pt-5">
        
        <!-- Column -->
        <div class="col-xl-6">
            <div class="view overlay">
            
                <img src="{{ product.image.url }}" alt="{{ product.name }}" class="img-fluid">
            </div>
        </div>

        <!-- Column -->
        <div class="col-xl-6">
            <h2>{{ product.name }}</h2>

            <div class="">
                {{ product.description }}
            </div>

            <hr class="my-3">

            <p class="">
                <del class="text-center">{{ product.price }}</del>
            </p>

            <div class="font-weight-bold display-4">
                
                <span class="badge badge-primary">{{ product.get_price }} &#8381;</span>
                {% if product.sale %}
                    <span class="badge red z-depth-1 mr-1"> -{{ product.sale }}%</span>
                {% endif %}
            </div>

            {% if product.characteristic_set.all %}
                <div class="mt-2">
                    <h3>Характеристики</h3>
                    <div>
                        {% for item in product.characteristic_set.all %}
                            <p class="mb-2">
                                <b>{{ item.paramether.name }}:</b> {{ item.value }} {{ item.paramether.units }}
                            </p>
                        {% endfor %}
                    </div>
                </div>
            {% endif %}

            <hr class="my-3">

            {% if product.avalible %}
                <div class="">
                    <a class="btn btn-primary" href="{% url 'cart:cart_add' product.id %}">Добавить в корзину</a>
                </div>
            {% else %}
                <button type="button" class="btn btn-primary" disabled>Продукта нет на складе</button>
            {% endif %}
        </div>
    </div>

    <section class="mt-2">
        <h2 class="text-center">Отзывы</h2>

        <hr class="my-3">

        {% if request.user.is_authenticated %}
            <form action="{% url 'catalog:leave_comment' product.id %}" method="POST" class="">

                {% csrf_token %}

                <div class="radio-group">
                    <div class="item">
                        <input type="radio" name="rate" class="custom-radio" value="1" required id="radio-1">
                        <label for="radio-1"><i class="fa fa-star red-text"></i></label>
                    </div>
                    <div class="item">
                        <input type="radio" name="rate" class="custom-radio" value="2" required id="radio-2">
                        <label for="radio-2"><i class="fa fa-star orange-text"></i></label>
                    </div>
                    <div class="item">
                        <input type="radio" name="rate" class="custom-radio" value="3" required id="radio-3">
                        <label for="radio-3"><i class="fa fa-star yellow-text"></i></label>
                    </div>
                    <div class="item">
                        <input type="radio" name="rate" class="custom-radio" value="4" required id="radio-4">
                        <label for="radio-4"><i class="fa fa-star green-text"></i></label>
                    </div>
                    <div class="item">
                        <input type="radio" name="rate" class="custom-radio" value="5" required id="radio-5">
                        <label for="radio-5"><i class="fa fa-star text-primary"></i></label>
                    </div>
                </div>
                <textarea name="text" id="comment" class="form-control md-form rate-slider show-trigger" maxlength='2048'placeholder="Напишите комментарий"></textarea>
                
                <button class="btn btn-danger ml-0"type="reset show-class">Отмена</button>
                <button class="btn btn-primary mr-0" type="submit show-class">Отправить</button>
            </form>
        {% endif %}

        <div class="d-flex flex-column">

            {% for item in product.comment_set.all %}
                <div class="py-2">
                    <h3 class="">{{ item.author }}</h3>

                    <time class="text-muted font-weight-light">{{ item.date }}</time>

                    <p>
                        {% for i in item.get_star_bright  %}
                            <i class="fa fa-star text-primary"></i>
                        {% endfor %}                        
                        {% for i in item.get_star_dusk %}
                            <i class="fa fa-star grey-text"></i>
                        {% endfor %}
                    </p>

                    <p>{{ item.text }}</p>
                </div>

            {% empty %}
                <p class="text-muted text-center">Отзывов пока что нет</p>
            {% endfor %}

        </div>
    </section>
   
{% endblock main%}

{% block script %}
{% endblock script %}

templates/catalog/index.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}" type="text/css">
{% endblock style %}

{% block header %}
  <!--Carousel Wrapper-->
<div class="container">
  <div id="carousel" class="carousel slide carousel-fade" data-ride="carousel">
    <!--Indicators-->
    <ol class="carousel-indicators">
      <li data-target="#carousel" data-slide-to="0" class="active"></li>
      <li data-target="#carousel" data-slide-to="1"></li>
      <li data-target="#carousel" data-slide-to="2"></li>
    </ol>
    <!--/.Indicators-->
    <!--Slides-->
    <div class="carousel-inner" role="listbox">
      <div class="carousel-item active">
        <div class="view">
          <img class="d-block img-fluid" src="{% static 'img/carousel/pexels-jeshootscom-442576.jpg' %}"
            alt="Photo by JESHOOTS.com from Pexels">
          <div class="mask rgba-white-light"></div>
        </div>
        <div class="carousel-caption">
          <h3 class="h3-responsive">Dualshock 4</h3>
          <p>Новое поступление геймпадов Dualshock 4 для Sony PS4.</p>
          <a href="#" class="btn btn-default">Купить</a>
        </div>
      </div>
      <div class="carousel-item">
        <!--Mask color-->
        <div class="view">
          <img class="d-block img-fluid" src="{% static 'img\carousel\pexels-pixabay-371924.jpg' %}"
            alt="Photo by Pixabay from Pexels">
          <div class="mask rgba-white-light"></div>
        </div>
        <div class="carousel-caption">
          <h3 class="h3-responsive">Nintendo Switch</h3>
          <p>Новое поступление насадок на джойконы для Nintendo Switch</p>
          <a href="#" class="btn btn-default">Купить</a>
        </div>
      </div>
      <div class="carousel-item">
        <!--Mask color-->
        <div class="view">
          <img class="d-block img-fluid" src="{% static 'img\carousel\pexels-garrett-morrow-682933.jpg' %}"
            alt="Photo by Garrett Morrow from Pexels">
          <div class="mask rgba-white-light"></div>
        </div>
        <div class="carousel-caption">
          <h3 class="h3-responsive">Насадки на Dualshock 4</h3>
          <p>В продаже появились насадки красного, жёлтого и синего цвета</p>
          <a href="#" class="btn btn-default">Купить</a>
        </div>
      </div>
    </div>
    <!--/.Slides-->
    <!--Controls-->
    <a class="carousel-control-prev" href="#carousel" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
    <!--/.Controls-->
  </div>
  <!--/.Carousel Wrapper-->
</div>
{% endblock header %}

{% block main %}


  <section class="text-center mb-4 wow">

    <h2 class="text-center"><a name="catalog">Каталог</a></h2>

    <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Категории:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav" aria-controls="basicExampleNav"
          aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link mr-1" href="/">Всё
                <span class="sr-only">(текущая)</span>
              </a>
            </li>
            {% for item in PRODUCT_TYPE %}
                <li class="nav-item{% if TITLE == item.verbose %} active{% endif %}">
                    <a class="nav-link mx-1" href="{% url 'category' item.name %}">{{ item.plural }}</a>
                </li>
            {% endfor %}
          </ul>
          <!-- Links -->

          <form class="form-inline" action="{% url 'search' %}" method="POST">
            <div class="md-form my-0">
                {% csrf_token %}
                <input class="form-control mr-sm-2" type="text" name="query" placeholder="Поиск" aria-label="Search">
            </div>
        </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

        <!-- Catalog -->
          {% if catalog %}
            <div class="row">
            {% for item in catalog %}
            <div class="col-lg-3 col-md-6 mb-4">
              <!-- Card -->
              <div class="card">
                  <!-- Imgae -->
                  <div class="view overlay">
                    <img src="{{ item.image.url  }}" class="img-fluid" alt="{{ item.name }}">
                    <a href="{% url 'catalog:detail' item.id %}">
                      <div class="mask rgba-white slight"></div>
                    </a>
                  </div>
                  <!-- Content -->
                  <div class="card-body text-center">
                    <a href="{% url 'category' item.product_type.name %}" class="text-grey">{{ item.product_type.verbose }}</a>

                    <a href="{% url 'catalog:detail' item.id %}" class="grey-text ">
                      <h5>{{ item.name }}</h5>
                    </a>

                    {% if item.avalible %}
                      {% if item.sale %} <h6 class="text-grey"><del>{{ item.price }}</del> &#8381;</h6>{% endif %}
                      <h4 class="font-weight-bold primary-text">{{ item.get_price|floatformat:2 }} &#8381;
                      {% if item.sale %} <span class="badge red z-depth-1 ml-1 rounded-pill">-{{ item.sale }}%</span> {% endif %}</h4>
                    {% else %}
                      <h4 class="font-weight-bold primary-text">Нет на складе</h4>
                    {% endif %}
                  </div>
              </div>
            </div>
            {% endfor %}
          {% else %}
          <div class="text-mute text-center">
            Продуктов нет
          </div>
          {% endif %}
    </section>

    
  <!-- Section benefits -->

  <section class="mb-4 wow fadeIn">
    <h2 class="text-center"><a name="benefits">Преимущества</a></h2>

    <div class="row align-items-stretch">

      <div class="col-md-6 py-4 mb-5">
        <div class="d-flex justify-content-start align-items-center my-2">
          <i class="fas fa-box-open text-primary h3 mr-2"></i>
          <h3 class="">Быстрая доставка</h3>
        </div>
        <div class="text-grey">
          Доставим ваш заказ по России за 12 дней
        </div>
      </div>

      <div class="col-md-6 py-4">

        <div class="d-flex justify-content-start align-items-center my-2">
          <i class="fas fa-wallet text-primary h3 mr-2"></i>
          <h3 class="">Самая низкая цена</h3>
        </div>
        <div class="text-grey">
          Ниже чем у конкурентов
        </div>
      </div>

    </div>

    <div class="row align-items-stretch">

      <div class="col-md-6 py-4 mb-5">
        <div class="d-flex justify-content-start align-items-center my-2">
          <i class="fas fa-user-shield text-primary h3 mr-2"></i>
          <h3 class="">Защита покупателей</h3>
        </div>
        <div class="text-grey">
          В течении недели любой возврат без объяснения причин
        </div>
      </div>

      <div class="col-md-6 py-4 mb-5">
        <div class="d-flex justify-content-start align-items-center my-2">
          <i class="fas fa-user-nurse text-primary h3 mr-2"></i>
          <h3 class="">Отзывчивая поддержка</h3>
        </div>
        <div class="text-grey">
          Поддержка работает 24/7. Отвечает в течении 5 минут
        </div>
      </div>

    </div>

  </section>

  <section class="mb-2">
    <h2 class="text-center"><a name="about">Информация</a></h2>
    <!-- Info -->
    <div id="accordion" role="tablist" aria-multiselectable="true">
      <div class="card">
        <div class="card-header" role="tab" id="headingOne">
          <h5 class="mb-0">
            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
              Доставка
            </a>
          </h5>
        </div>

        <div id="collapseOne" class="collapse show" role="tabpanel" aria-labelledby="headingOne">
          <div class="card-block px-2">
            {% lorem 2 b random %}
          </div>
        </div>
      </div>
      <div class="card">
        <div class="card-header" role="tab" id="headingTwo">
          <h5 class="mb-0">
            <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
              Оплата
            </a>
          </h5>
        </div>

        <div id="collapseTwo" class="collapse" role="tabpanel" aria-labelledby="headingTwo">
          <div class="card-block px-2">
            {% lorem 2 b random %}
          </div>
        </div>
      </div>
      <div class="card">
        <div class="card-header" role="tab" id="headingThree">
          <h5 class="mb-0">
            <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
              Защита покупателей
            </a>
          </h5>
        </div>
        <div id="collapseThree" class="collapse" role="tabpanel" aria-labelledby="headingThree">
          <div class="card-block px-2">
            {% lorem 1 b random %}
          </div>
        </div>
      </div>
    </div>

    <div class="text-center">
      <p>
      Проект является макетом настоящего онлайн магазина и не предоставляет возможности реальной покупки товаров. 
      </p>
      <p>
      Все права пренадлежат их собственникам
      </p>
    </div>
  </section>


{% endblock main %}

{% block srtipt %}
    <script src="{% static 'js/index.js' %}"></script>
    <script>
      $('#carousel').carousel({
        touch : true,
      });
    </script>
{% endblock srtipt %}